- name: add rabbit admin user 
  rabbitmq_user:
    user: admin
    password: admin
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    tags: administrator
    state: present
  run_once: true

- name: add rabbit {{rabbitmq_user}} user 
  rabbitmq_user:
    user: '{{rabbitmq_user}}'
    password: '{{rabbitmq_password}}'
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  run_once: true
